version: 2
jobs:
  build-test-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --pure-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          name: Save Yarn Package Cache
          paths:
            - ~/.cache/yarn
      - run:
          name: test
          command: yarn ci
      - deploy:
          command: bin/deploy.sh

workflows:
  version: 2
  next_seed_workflow:
    jobs:
      - build-test-deploy
